name: cockroach

on:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/cockroach.yaml"
    - "COCKROACH_VERSION.txt"

jobs:
  build-cockroach:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set cockroach version
      id: cockroach-version
      run: echo "::set-output name=cockroach_version::$(cat COCKROACH_VERSION.txt)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64,linux/amd64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: Dockerfile
        platforms: linux/arm64,linux/amd64
        build-args: |
          COCKROACH_VERSION=${{ steps.cockroach-version.outputs.cockroach_version }}
        tags: |
          steven0351/cockroachdb:latest
          steven0351/cockroachdb:${{ steps.cockroach-version.outputs.cockroach_version }}